name: CI/CD Deploy

on:
  push:
    branches:
      - main  # Chạy khi push vào branch main

jobs:
  deploy-backend:
    # Chỉ chạy nếu có thay đổi trong thư mục backend/
    if: github.event_name == 'push' && contains(github.event.commits.*.modified, 'project-2-backend/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-2-backend  # Thiết lập thư mục làm việc là backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Phiên bản Node.js, thay nếu cần (kiểm tra package.json trong backend)

      - name: Install dependencies
        run: npm ci  # Sử dụng npm ci để cài đặt nhanh và đúng dependencies

      - name: Run tests
        run: npm test || true  # Chạy test, thêm || true để không fail nếu chưa có test

      - name: Build backend
        run: npm run build || true  # Chạy build nếu có, bỏ qua nếu không cần

      - name: Create deployment package
        run: zip -r project-2-backend.zip . -x "*.git*"  # Zip thư mục backend, loại trừ .git

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: ${{ github.sha }}  # Dùng commit SHA làm version label
          region: ${{ secrets.AWS_REGION }}
          deployment_package: project-2-backend.zip
        env:
          WORKING_DIRECTORY: project-2-backend

  deploy-frontend:
    # Chỉ chạy nếu có thay đổi trong thư mục frontend/
    if: github.event_name == 'push' && contains(github.event.commits.*.modified, 'project-2-frontend/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-2-frontend  # Thiết lập thư mục làm việc là frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Phiên bản Node.js cho Next.js, thay nếu cần

      - name: Install dependencies
        run: npm ci  # Cài đặt dependencies cho frontend

      - name: Run tests
        run: npm test || true  # Chạy test, bỏ qua nếu chưa có

      - name: Build frontend
        run: npm run build  # Build Next.js (bắt buộc cho Vercel)

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: project-2-frontend
          vercel-args: '--prod'  # Deploy lên production
