name: CI/CD Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'project-2-backend/**'  # Theo dõi thay đổi trong backend
      - 'project-2-frontend/**'  # Theo dõi thay đổi trong frontend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-2-backend
    if: contains(github.event_name, 'push') && github.event.commits
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
        working-directory: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || true

      - name: Build backend
        run: npm run build || true

      - name: Create deployment package
        run: zip -r project-2-backend.zip . -x "*.git*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: project-2-backend.zip
        env:
          WORKING_DIRECTORY: project-2-backend

  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-2-frontend
    if: contains(github.event_name, 'push') && github.event.commits
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
        working-directory: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || true

      - name: Build frontend
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: project-2-frontend
          vercel-args: '--prod'
